packages:
  - .

patchedDependencies:
  "@nuxt/content": patches/@nuxt__content.patch
onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
