overrides:
  h3: <2 # remove on nuxt 5 release
  typescript: npm:typescript-native-bridge@^6.0.3-bridge.16.tsgo.7.0.2
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAge: 0
